version: '3.8'

services:
  app:
    build: .
    container_name: readfile-demo
    ports:
      - "11111:11111"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped 